### ISSUE TITLE
Can't seek with the mpv backend (in 1.1.0a2)

### ISSUE THREAD

**Issue by KireinaHoro** [cosven/FeelUOwn#222]
Here's a screenshot of the progress bar. Clicking / dragging makes no difference, not affecting the music playback either.

![2017-07-13-020756_682x258_scrot](https://user-images.githubusercontent.com/7804730/28132688-1e9323f6-6770-11e7-9924-e71b6c392619.png)

**Comment by KireinaHoro** [comment]
When using 1.0.5.3 (with gst-plugins-soup), the progress bar do display the progress correctly, yet trying to seek stops the playback and results in a 

```
Error: "Internal data stream error."
```

on the console.

**Comment by cosven** [comment]
bases on past practice, people use different linux distribution have a lot of problems in installing packages related to gstreamer. 
especially people who use fedora have great problem in installing gstreamer correctly.


I choose to give up gstreamer because:
1. different qt version depend on different gstreamer lib, the os version matters.
2. gstreamer have many plugin, these plugin have different name in different linux distribution. it is hard for me to maintain install script.

**Comment by KireinaHoro** [comment]
So basically it's `fuocore` that needs improving. maybe?

**Comment by KireinaHoro** [comment]
BTW actually you don't need to maintain some install script or so. This will create burdens for packagers. IMO the appropriate practice is to list out the dependencies clearly and provide appropriate build instructions so that packagers are happy, and (if applicable) provide packages (.deb, .rpm, .tar.xz, etc) to end users.

**Comment by cosven** [comment]
That's right. 
I will list all dependencies in  readme later ~

but return back to the title, I can seek in osx (1.1.0a2).Is there any error info as you can not seek.
can you check your `fuocore` version which should be `>=v0.0.5a5`

**Comment by KireinaHoro** [comment]
`=dev-python/fuocore-0.0.5_alpha5`

**Comment by cosven** [comment]
新版本应该没这个问题了
