### ISSUE TITLE
change data folder from ~/.FeelUOwn to ~/Music/FeelUOwn or ~/FeelUOwn

### ISSUE THREAD

**Issue by chen-chao** [cosven/FeelUOwn#236]
The data folder should be in ~/Music If it exists, and there is no need to hide it.

**Comment by cosven** [comment]
**This is one of my impulsive decisions.**

From the very start, the `~/.FeelUOwn` folder was created to stores user secrets. As the app grows, I put more and more things in this directory, including media files, image cache, plugins, etc. This is not a very good practice, but it's **acceptable** since many linux application(vim/emacs/dropbox/thunderbird) create their own (hidden) directory in home. **In addition, the backward compatibility matters.**

However, there is actually a [specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) about application directory settings. There is also a dicussion on [stackoverflow](https://stackoverflow.com/a/1024339), which tells us which is the proper directory for  applications. As we can know from the XDG base directory specification, the `~/.cache` maybe the best directory to store app data cache, `~/.config/` is the correct directory for app settings, and the `~/.local/share` directory is appropriate for app data. 

**Therefore, I think `~/.local/share/feeluown/songs` is probably the right directory for feeluown songs.** In order to make other players auto discover feeluown songs, we can create a soft link in ~/Music/. For example: `ln -sf ~/.local/share/feeluown/songs ~/Music/feeluown`. For now, we can do this by `ln -sf ~/.FeelUOwn/songs ~/Music/feeluown`.

I'm curius about why your thought the data folder should be `~/FeelUOwn`, what is your consideration? Glad to have a discussion here. XD

Las but not least, thank you for your suggestions ~

**Comment by chen-chao** [comment]
Thank you for the long reply, as I didn't think deeply when I opened this issue. 

My only consideration is that a **normal app** does not need to hide **data**(not cache or config files) from its user. User should be able to access the songs data(like downloaded songs or saving playlists). That's why I think ~/Music is a proper place. Since not all users have the music folder and feeluown provides cli-only mode, ~/FeelUOwn is also acceptable.

As for backward compatibility, you could move the current .feeluown to ~/Music if it exists when updating if you were to make such a decision.  

This is not a "real" problem anyway. I will close it as you've already fully considered the suggestion.
